"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.8.
"""
from corsheaders.defaults import default_headers
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-sb)ez%wqh9ggix&gs=uf+#m0(1#(_%ua=l-yaq-*u&5@2dhpr5'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# ----------------------------------------------------------
# APPLICATIONS
# ----------------------------------------------------------

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third-party apps
    'rest_framework',
    'corsheaders',

    # Your app
    'tracker',
]

# ----------------------------------------------------------
# MIDDLEWARE
# ----------------------------------------------------------

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # added for frontend access
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# ----------------------------------------------------------
# DATABASE (SQLite for now — MySQL will be added later)
# ----------------------------------------------------------

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'finance_tracker',     # your DB name
        'USER': 'root',                # your MySQL username
        'PASSWORD': 'flowerdrew162005',
        'HOST': 'localhost',
        'PORT': '3306',
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        },
    }
}


# ----------------------------------------------------------
# PASSWORD VALIDATION
# ----------------------------------------------------------

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# ----------------------------------------------------------
# INTERNATIONALIZATION
# ----------------------------------------------------------

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'  # changed to your local timezone

USE_I18N = True

USE_TZ = True


# ----------------------------------------------------------
# STATIC FILES
# ----------------------------------------------------------

STATIC_URL = 'static/'


# ----------------------------------------------------------
# DEFAULT PRIMARY KEY FIELD TYPE
# ----------------------------------------------------------

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ----------------------------------------------------------
# DJANGO REST FRAMEWORK CONFIGURATION
# ----------------------------------------------------------

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
}

# ----------------------------------------------------------
# CORS CONFIGURATION
# ----------------------------------------------------------

CORS_ALLOWED_ORIGINS = [
    "http://127.0.0.1:5500",   # Frontend (VS Code Live Server)
    "http://localhost:5500",
]

# ✅ Add this line (important for Authorization headers)
CORS_ALLOW_HEADERS = list(default_headers := [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
])

# ✅ Optional: Allow all methods (POST, GET, DELETE, etc.)
CORS_ALLOW_ALL_METHODS = True

# ✅ Fix common token authentication issue
CORS_ALLOW_CREDENTIALS = True