# Generated by Django 5.2.8 on 2025-11-09 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('food', 'Food'), ('travel', 'Travel'), ('shopping', 'Shopping'), ('grocery', 'Grocery'), ('salary', 'Salary'), ('entertainment', 'Entertainment'), ('bills', 'Bills'), ('others', 'Others')], default='others', max_length=50),
        ),
    ]
